Update validation-pipeline.yml

diff --git a/.github/workflows/validation-pipeline.yml b/.github/workflows/validation-pipeline.yml
--- a/.github/workflows/validation-pipeline.yml
+++ b/.github/workflows/validation-pipeline.yml
@@ -12,10 +12,11 @@ on:
 
   pull_request:
 
+
 jobs:
 
 # =========================
-# JOB 1 - CHECK DOCKERFILE
+# JOB 1 - CHECK DOCKERFILE EXISTS
 # =========================
   dockerfile-check:
     runs-on: ubuntu-latest
@@ -24,9 +25,13 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Check Dockerfile Exists
+      - name: Verify Dockerfile Exists
         run: |
-          ls Dockerfile
+          if [ ! -f Dockerfile ]; then
+            echo "Dockerfile not found!"
+            exit 1
+          fi
+          echo "Dockerfile found ✅"
 
 
 # =========================
@@ -41,13 +46,16 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Install Checkov
-        run: pip install checkov
+        run: |
+          pip install --upgrade checkov
 
+      # ===== Console Scan (Readable Output)
       - name: Run Checkov Scan (Console)
         run: |
           checkov -d . \
           --framework dockerfile,github_actions
 
+      # ===== SARIF Report (GitHub Security Tab)
       - name: Generate SARIF Report
         run: |
           checkov -d . \
@@ -55,7 +63,7 @@ jobs:
           -o sarif \
           --output-file-path checkov-report.sarif
 
-      - name: Upload Checkov Report
+      - name: Upload Checkov Report Artifact
         uses: actions/upload-artifact@v4
         with:
           name: checkov-security-report
