Update validation-pipeline.yml

diff --git a/.github/workflows/validation-pipeline.yml b/.github/workflows/validation-pipeline.yml
--- a/.github/workflows/validation-pipeline.yml
+++ b/.github/workflows/validation-pipeline.yml
@@ -2,3 +2,41 @@ name: Validation Pipeline
 
 on:
   pull_request:
+
+jobs:
+
+  dockerfile-check:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Check Dockerfile Exists
+        run: |
+          if [ ! -f Dockerfile ]; then
+            echo "Dockerfile not found"
+            exit 1
+          fi
+
+
+  security-scan:
+    runs-on: ubuntu-latest
+    needs: dockerfile-check
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install Checkov
+        run: pip install checkov
+
+      - name: Run Checkov Scan
+        run: |
+          checkov -d . \
+          --output html \
+          --output-file-path checkov-report.html
+
+      - name: Upload Checkov Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: checkov-security-report
+          path: checkov-report.html
